language: android
env:
  global:
  - ANDROID_API=26
  - ANDROID_BUILD_TOOLS=26.0.2
  - PROJECT_2=HelloToast
  - PROJECT_3=ScrollingText2
  - secure: 1zkGmn2+GLK77JrzZSWlDTXdWXphyL4E/le6ivGYSFDMJH3i/e9ccn0rIlUHzQZQoSAauicItlFv2q783i+6hdhX+8manB/Do/ijavc4MJKz3zy6JH16N+AQE+nP7MfE2fOaiYtPUpQ6cYBW4AXX8OkuHCOCVJhZ1+pelnbFiOz5/RJ1YUHSn8i7GDXQj2e8g9tyTmwQ1HP+BgoZuBpeamORkUW3tr37T792dofGQjRNVpKp4ZBWDKR15GjMgauQXYrIX7sQr3qn6JFsJojJepoNOTdMVabYSlIKaJs/Thjyyglh4MayZi4063tpVdHWwgqfYI+OznHUeo8rbmgdqjyI+6kkkRWTqhx78YtRGvniL9rDzZ1hgfGbV2j1jko73ndk9QrjEf5WgFZKCqiFcX1vXbgNfJugC1E6Hq9q+0KhlLlrsrcWQEiv5L0XH37JIGAZ/jqxkUNa3tKUQpJBmlnDCzU4Pgo5zBu6thdp3ancXGGeW4cX6J7GiduUWFmsyK7FE85mZUHOeZafKMKvhjEHKlJ9kv4Bs9J4013peyuY2dxaJH5AvuN0FBqreAZV9CDa34RhU9uoS2r1SF8j8v8YuQlt2IvusZQOMKOIXEftIuMgIqInY9DS5FrQgChawVmJc46AlUefsIWJlbiYgejXHADQDdChEY/EibpxTPI=
  - secure: CQGZHDnIW2G3Uo/X530wL8bsARI3QE+AghNv4BdtXfhn/nMjVpIykiFXafyOkKeIkWcvgFnquiDgeMNDn5Qy4rn6EXqSW01zfBbz/UEdyVQJ8mRH0CM+FuxYiq7wOxwlG9t43S5hSRLbjMUrcETri1IPPC3695yJR+XD4hu0nTAiOKHZR2L5DD8PHqvEEkJyPtcC4gHhKN+mBFK3nwZUaQfEPp6P41+rbQQl2HvP4xsZMq7SkT5TXmzvng5zc1BgyBXtnOaMcutH9+GfLwBsa8jYbzjBM6i7I12MSgLk+1ltDA7/i0spTXWHn9d3Lz3pGZZNq1qmi4AYGnnEzkKwI3T16IqLDaN4iWpJaCgG+n/hCaGWwp4ZUFq/rF6mjxaFUa0awHZ1cSpwDay8hgoyWi4MNzL8wh5zHpBY8sYtPmYvw5BIP9CHLb2xffJu6n5FoCt4aGTfupmz++MTiegb2N8tj08CDJ9g8hV6eatp8d0dbJaDxgEzDpnLGJ1EpdWkhViE4jlmo34plqUQl1FW499qZZ7SUNPROhI2EiP9OyX+eVayS/zqXVNkzXTsKgdwfBC3LZy+tW2/VKN762zpTto2Pugp3PktkTNw/ulPj6irTIqIsz3kUISVVsByTPQ+Z4Hk5C0c8hEMn7B7SayJe8/h6ctHKASwwDLLmp+AnYw=
branches:
  only:
  - master
android:
  components:
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - extra-android-m2repository
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
before_install:
- export PROJECT_ROOT="${PWD}"
- chmod +x ${PROJECT_2}/gradlew
- chmod +x ${PROJECT_3}/gradlew
- chmod +x result_parser.py
before_script:
- adb kill-server
- adb connect ${EMULATOR_SERVER}
- adb devices
script:
- cd ${PROJECT_ROOT}
- cd ${PROJECT_2} && ./gradlew connectedDebugAndroidTest --stacktrace
- cd ${PROJECT_ROOT}
- cd ${PROJECT_3} && ./gradlew connectedDebugAndroidTest --stacktrace
after_script:
- cd ${PROJECT_ROOT}
- "./result_parser.py ${PROJECT_ROOT}/${PROJECT_2}/app/build/reports/androidTests/connected/com.example.android.hellotoast.ChangeAnAppTest.html
  >> results.txt"
- "./result_parser.py ${PROJECT_ROOT}/${PROJECT_3}/app/build/reports/androidTests/connected/com.example.android.scrollingtext.ChangeAnAppTest.html
  >> results.txt"
- echo $(basename ${TRAVIS_REPO_SLUG}) ${TRAVIS_BRANCH} ${TRAVIS_COMMIT} $(git show
  -s --format=%ci ${TRAVIS_COMMIT} | cut -c 1-20) $(cat results.txt) > results.txt
- awk  '//{for(i=6;i<NF;i=i+2) print $i"\t"$(i+1)}' results.txt
- curl -d "@results.txt" -X POST ${DB_SERVER_URL}
